### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDAnalysis-workshop#1]
We need to give users instructions for how to install MDAnalysis on their own machines _before_ the workshop starts. We rather have the participants install their own instead of providing cloud instances because experiences shows that users need to know that they can set up the software themselves.

We support **Linux** and **Mac OS X**.

We need
- [x] web page with installation instructions (can be a wiki page here)
- [x] repository or server with data (e.g. @orbeckst's unlimited ASU Dropbox?) --- see #3 

What kind of installers should we support?
- `pip` (+ `apt-get`) — see the VM recipes
- `conda` (see the MDA travis.xml)

EDIT
- removed "script for downloading bits and pieces" — can be added to #3 if necessary

**Comment by dotsdl** [comment]
What do we do about Windows machines? There are bound to be a few.

**Comment by orbeckst** [comment]
On 29 Sep, 2015, at 17:05, David Dotson wrote:

> What do we do about Windows machines? There are bound to be a few.

VMs or bootable Linux or cloud instance. We don't have a working version of MDAnalysis under Windows, see MDAnalysis/mdanalysis#450

**Comment by orbeckst** [comment]
For setting up python: maybe follow http://physics.codes/ and use the miniconda approach?

**Comment by dotsdl** [comment]
I'll test the existing vagrantfile, using miniconda to get the python package dependencies.

**Comment by orbeckst** [comment]
For a first draft see [notebooks/CECAM_2015_preparations.ipynb](https://github.com/Becksteinlab/MDAnalysis-workshop/blob/master/notebooks/CECAM_2015_preparations.ipynb) but this 
- needs to be tested
- should be turned into nicer static pages (sphinx or Jekyll + mdanalysis.org theming)

**Comment by orbeckst** [comment]
conda works; I tried it in a fresh Ubuntu 14.04 VM. 
The notebook is ugly, though, so this needs to be turned into a static webpage. I gravitate to replacing the existing sphinx pages (because that already builds automatically and it is easy to add links to docs via intersphinx links).

**Comment by orbeckst** [comment]
http://becksteinlab.github.io/MDAnalysis-workshop/installation.html
